apiVersion: v1
kind: Secret
metadata:
  name: quotes-api-secrets
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "Host=quotes-postgres;Port=5432;Database=quotesdb;Username=quotesuser;Password=quotespass"
  Jwt__Key: "JpWX4hRQ9EP8XGE25LJx3pQtqMHYTUw2V2eERuD8Hy9ZAWHJUREh7wYJUs1AVYot+QdxnpkFGYXi4WPMWOmcCg==JpWX4hRQ9EP8XGE25LJx3pQtqMHYTUw2V2eERuD8Hy9ZAWHJUREh7wYJUs1AVYot+QdxnpkFGYXi4WPMWOmcCg=="
  Jwt__Issuer: "QuotesAggregator"
  Jwt__Audience: "QuotesAggregatorClients"