apiVersion: v1
kind: Service
metadata:
  name: quotes-postgres
  labels:
    app: quotes-postgres
spec:
  type: ClusterIP
  selector:
    app: quotes-postgres
  ports:
    - name: pg
      port: 5432
      targetPort: 5432